(
    GOAL, SITUATION, EXPERIENCE, WEIGHT, HEIGHT, AGE,
    TRAINING_DAYS, SESSION_LENGTH, CURRENT_SPLIT, INJURIES,
    GUT_HEALTH, SLEEP, STRESS, STEPS, CAFFEINE,
    SUPPLEMENTS, MEDICAL,
    ED_SCREENING_1, ED_SCREENING_2, ED_SCREENING_3, ED_SCREENING_4,
    CONFIRM_PROFILE,
    CHECKIN_WEIGHT, CHECKIN_WAIST, CHECKIN_SLEEP, CHECKIN_READINESS,
    CHECKIN_SORENESS, CHECKIN_ADHERENCE, CHECKIN_TOP_SETS,
    COACH_CHAT,
    HYDRATION, ALCOHOL_WEEKLY, WORK_SCHEDULE, MOBILITY, BLOODWORK,
    RAPID_WEIGHT_LOSS, MENTAL_HEALTH,
    CRISIS_INTERVENTION,
) = range(38)
