 "Dumbbell Bench Press":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[6,12],subs:["Bench Press","Machine Chest Press","Dumbbell Incline Press","Floor Press"]},
 "Machine Chest Press":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[8,15],subs:["Bench Press","Dumbbell Bench Press","Machine Incline Press","Floor Press"]},
 "Dumbbell Incline Press":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[6,12],subs:["Incline Chest Press","Machine Incline Press","Dumbbell Bench Press","Bench Press"]},
 "Machine Incline Press":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[8,15],subs:["Incline Chest Press","Dumbbell Incline Press","Machine Chest Press","Bench Press"]},
 "Dumbbell Flies":{t:"isolation",f:"low",jr:["shoulder"],inc:2.5,rr:[10,15],subs:["Machine Chest Flies","Cable Flies","Pec Deck","Push-Up"]},
 "Cable Flies":{t:"isolation",f:"low",jr:["shoulder"],inc:2.5,rr:[10,15],subs:["Machine Chest Flies","Dumbbell Flies","Pec Deck","Push-Up"]},
 "Pec Deck":{t:"isolation",f:"low",jr:["shoulder"],inc:2.5,rr:[10,15],subs:["Machine Chest Flies","Cable Flies","Dumbbell Flies","Push-Up"]},
 "Floor Press":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[6,10],subs:["Bench Press","Close-Grip Bench","Dumbbell Bench Press","Machine Chest Press"]},
 "Push-Up":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[10,20],subs:["Bench Press","Machine Chest Press","Floor Press","Dumbbell Bench Press"]},
 "Chest Dip":{t:"compound",f:"high",jr:["shoulder","elbow"],inc:2.5,rr:[6,12],subs:["Bench Press","Dumbbell Bench Press","Push-Up","Machine Chest Press"]},
 // ── Pool expansion (back) ──
 "Chest-Supported Row":{t:"compound",f:"moderate",jr:["shoulder","spine"],inc:2.5,rr:[8,15],subs:["Seated Cable Row","T-Bar Row","Dumbbell Row","Meadows Row"]},
 "Seated Cable Row":{t:"compound",f:"moderate",jr:["shoulder","spine"],inc:2.5,rr:[6,12],subs:["Seated Row","Chest-Supported Row","Dumbbell Row","T-Bar Row"]},
 "Dumbbell Row":{t:"compound",f:"moderate",jr:["shoulder","spine"],inc:2.5,rr:[6,12],subs:["Barbell Row","Chest-Supported Row","Seated Cable Row","Meadows Row"]},
 "Meadows Row":{t:"compound",f:"moderate",jr:["spine","shoulder"],inc:2.5,rr:[6,12],subs:["T-Bar Row","Chest-Supported Row","Dumbbell Row","Barbell Row"]},
 "Chin-Up":{t:"compound",f:"high",jr:["shoulder","elbow"],inc:-1,rr:[6,12],subs:["Pull-Up","Lat Pulldown","Assisted Pull-Up","Inverted Row"]},
 "Assisted Pull-Up":{t:"compound",f:"high",jr:["shoulder","elbow"],inc:-1,rr:[6,12],subs:["Pull-Up","Lat Pulldown","Chin-Up","Inverted Row"]},
 "Straight-Arm Pulldown":{t:"isolation",f:"low",jr:["shoulder"],inc:2.5,rr:[10,15],subs:["Cable Pullover","Lat Pulldown","Pull-Up","Seated Row"]},
 "Inverted Row":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[8,15],subs:["Pull-Up","Lat Pulldown","Seated Cable Row","Chest-Supported Row"]},
 "Cable Pullover":{t:"compound",f:"moderate",jr:["shoulder"],inc:2.5,rr:[8,15],subs:["Straight-Arm Pulldown","Lat Pulldown","Pull-Up","Seated Row"]},
 // ── Pool expansion (shoulders) ──
 "Seated DB Press":{t:"compound",f:"moderate",jr:["shoulder","spine"],inc:2.5,rr:[6,12],subs:["Overhead Press","Machine Shoulder Press","Arnold Press","Shoulder Press"]},
 "Machine Shoulder Press":{t:"compound",f:"moderate",jr:["shoulder"],inc:2.5,rr:[8,15],subs:["Overhead Press","Seated DB Press","Arnold Press","Shoulder Press"]},
 "Arnold Press":{t:"compound",f:"moderate",jr:["shoulder"],inc:2.5,rr:[8,15],subs:["Seated DB Press","Overhead Press","Machine Shoulder Press","Lateral Raise"]},
 "Cable Lateral Raise":{t:"isolation",f:"low",jr:["shoulder"],inc:1,rr:[10,20],subs:["Lateral Raise","Lean-Away Lateral Raise","DB Upright Row","Front Raise"]},
 "Lean-Away Lateral Raise":{t:"isolation",f:"low",jr:["shoulder"],inc:1,rr:[10,20],subs:["Lateral Raise","Cable Lateral Raise","DB Upright Row","Front Raise"]},
 "Front Raise":{t:"isolation",f:"low",jr:["shoulder"],inc:1,rr:[10,20],subs:["Lateral Raise","Cable Lateral Raise","Arnold Press","DB Upright Row"]},
 "Face Pull":{t:"isolation",f:"low",jr:["shoulder"],inc:2.5,rr:[10,20],subs:["Rear Delt Flies","Reverse Pec Deck","Bent-Over Cable Rear Delt","Wide Row"]},
 "Reverse Pec Deck":{t:"isolation",f:"low",jr:["shoulder"],inc:2.5,rr:[10,20],subs:["Rear Delt Flies","Face Pull","Bent-Over Cable Rear Delt","Wide Row"]},
 "Bent-Over Cable Rear Delt":{t:"isolation",f:"low",jr:["shoulder"],inc:1,rr:[10,20],subs:["Rear Delt Flies","Face Pull","Reverse Pec Deck","Wide Row"]},
 "DB Upright Row":{t:"isolation",f:"low",jr:["shoulder"],inc:1,rr:[10,15],subs:["Barbell Upright Row","Lateral Raise","Cable Lateral Raise","Front Raise"]},
 "Barbell Upright Row":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[8,12],subs:["DB Upright Row","Lateral Raise","Cable Lateral Raise","Arnold Press"]},
 "Wide Row":{t:"compound",f:"moderate",jr:["shoulder","spine"],inc:2.5,rr:[8,15],subs:["Rear Delt Flies","Seated Row","Face Pull","Chest-Supported Row"]},
 // ── Pool expansion (triceps) ──
 "Rope Pushdown":{t:"isolation",f:"low",jr:["elbow"],inc:2.5,rr:[8,15],subs:["Triceps Pushdown","Overhead Cable Extension","Skull Crusher","Close-Grip Bench"]},
 "Overhead Cable Extension":{t:"isolation",f:"low",jr:["elbow","shoulder"],inc:1,rr:[10,15],subs:["Triceps Overhead Ext","Rope Pushdown","Triceps Pushdown","Skull Crusher"]},
 "Skull Crusher":{t:"isolation",f:"low",jr:["elbow"],inc:2.5,rr:[8,15],subs:["Triceps Overhead Ext","Rope Pushdown","Close-Grip Bench","JM Press"]},
 "Close-Grip Bench":{t:"compound",f:"moderate",jr:["shoulder","elbow"],inc:2.5,rr:[6,10],subs:["Bench Press","JM Press","Triceps Pushdown","Floor Press"]},
 "JM Press":{t:"compound",f:"moderate",jr:["elbow"],inc:2.5,rr:[6,10],subs:["Close-Grip Bench","Skull Crusher","Triceps Pushdown","Bench Press"]},
 "Bench Dip":{t:"isolation",f:"low",jr:["elbow","shoulder"],inc:2.5,rr:[10,15],subs:["Triceps Pushdown","Rope Pushdown","Skull Crusher","Close-Grip Bench"]},
