 '.rp{display:flex;gap:10px;flex-wrap:wrap;margin:6px 0 12px}'+
 '.rp>div{flex:1;min-width:70px;background:rgba(20,21,26,.4);border-radius:6px;padding:7px 8px;text-align:center;border:1px solid rgba(250,250,248,.03)}'+
 '.rp .v{font-size:1rem;font-weight:700;color:#F4C93B}.rp .l{font-size:.48rem;text-transform:uppercase;letter-spacing:.5px;color:rgba(250,250,248,.2);margin-top:1px}'+
 'table{width:100%;border-collapse:collapse;margin:4px 0 8px}'+
 'th{text-align:left;font-size:.52rem;text-transform:uppercase;letter-spacing:1px;color:rgba(250,250,248,.25);padding:5px 6px 3px;border-bottom:1px solid rgba(250,250,248,.06);font-weight:500}'+
 'td{padding:4px 6px;font-size:.65rem;border-bottom:1px solid rgba(250,250,248,.02);color:rgba(250,250,248,.7)}'+
 '.c{text-align:center}.db{margin:8px 0 12px;background:rgba(20,21,26,.4);border-radius:8px;padding:8px 10px;border:1px solid rgba(250,250,248,.03)}'+
 '.dt{font-family:"Oswald",sans-serif;font-size:.8rem;text-transform:uppercase;letter-spacing:1px;color:#F4C93B;margin-bottom:4px}'+
 '.sec{margin:16px 0;page-break-inside:avoid}.ec{display:flex;flex-direction:column;gap:8px}'+
 '.ecard{background:rgba(20,21,26,.35);border-radius:8px;padding:8px 10px;border:1px solid rgba(250,250,248,.03)}'+
 '.ect{font-size:.65rem;font-weight:600;color:#FAFAF8;margin-bottom:5px;text-transform:uppercase;letter-spacing:.4px}'+
 '.etip{font-size:.6rem;color:rgba(250,250,248,.45);margin-top:6px;line-height:1.4}'+
 '.gs{display:flex;gap:8px;align-items:flex-start;padding:6px 8px;background:rgba(20,21,26,.25);border-radius:6px;margin-bottom:4px;border:1px solid rgba(250,250,248,.02)}'+
 '.gn{width:22px;height:22px;border-radius:50%;background:#F4C93B;color:#14151A;font-size:.65rem;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0}'+
 '.gs div{font-size:.62rem;color:rgba(250,250,248,.6);line-height:1.4}.gs div strong{color:#FAFAF8}'+
 '.ft{text-align:center;margin-top:24px;padding-top:10px;border-top:1px solid rgba(250,250,248,.04);font-size:.55rem;color:rgba(250,250,248,.2)}'+
 '.ft a{color:rgba(244,201,59,.35);text-decoration:none}'+
 '</style></head><body>'+
 '<h1>Your Training Program</h1>'+
 '<div class="sb">'+dateF+' \u2014 '+prog.splitName+' \u2014 '+ta+' \u2014 '+goal+' \u2014 '+dd+' days/wk</div>'+
 '<div class="rp"><div><div class="v">'+prog.days.length+'</div><div class="l">Training Days</div></div>'+
 '<div><div class="v">'+prog.totalSets+'</div><div class="l">Weekly Sets</div></div>'+
 '<div><div class="v">'+prog.totalEx+'</div><div class="l">Exercises</div></div>'+
 '<div><div class="v" style="text-transform:capitalize;font-size:.8rem">'+rec+'</div><div class="l">Recovery</div></div></div>'+
 edu+
 '<div class="st" style="color:#F4C93B">Your Volume Targets</div>'+
 '<table><thead><tr><th>Muscle</th><th class="c">Priority</th><th class="c">MEV</th><th class="c">MAV</th><th class="c">MRV</th><th class="c">Target</th></tr></thead><tbody>'+vh+'</tbody></table>'+
 '<div class="st" style="color:#F4C93B">Your Split &amp; Exercises</div>'+ph+
 gh+
 '<div class="ft">Generated by Muscle OS Training App \u2014 <a href="https://wa.me/201040796017">Coach Anas Mo\'men</a></div>'+
 '<footer class="mos-footer"><div class="mos-footer-inner"><div class="mos-fbrand">ANAS MO\'MEN <span>COACHING</span></div><div class="mos-fnav"><a href="../index.html">Home</a><a href="../tools/">Tools</a><a href="../guides/">Guides</a><a href="../books/">Books</a></div><div class="mos-fsocial"><a href="https://wa.me/201040796017">WhatsApp</a><a href="https://instagram.com/anas_moamen1">Instagram</a></div></div><div class="mos-fcopy">muscleos.coach \u2014 Coach Anas Mo\'men</div></footer>'+
 '<script src="../js/auth.js"><\/script>'+
'</body></html>');
 w.document.close();w.focus();setTimeout(function(){w.print();},500);
 });

 // ═══════════════════════════════════════
